language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: Vr06aXdkAccK8yLNUB8xaIPx97X9vCYYqQspA9MxwibOgMC82Fq04khgOs78WiMKcogKWk/Bj2soi/MZOhBDYQNFuFWP2Q4jcF8Dt43pFwPh5KcMCS3mFwjOWBkWhKRHVpoHRpLXaUQIeRMFZDSLavzdNzm6j3Od+X3qnLJ20HlltKUnxz7tpj7ELeGWZiEGqzGGpLdIZdX8cYIeGPPmmkLlZTLdvfN6ojEZqtRIse4REXv2TcoshVH1kOBCK+SZw0RANdfdUmq/Olrj+RtfGcsaUD5sPNVY8diB5AUDoMreFiorgLPyPnJ8oMRekrYbRO1YmpmIY/q8NNY4pe847bygXqvSRhs8Vf5DlAW97WZuoiMYYIKCE8i4TvVqhfhInNCnAm0YKot3qX84l37ASfkw8CS5ymWqImtARHpmpULBvA41ifkd3TUG0NuOQXYbxPICKWOuuzZty/eyyvjcrjD2nMZWeRuLKz4DtMn/S+tQ3cWC2amnHJ841pNm874GIOM6b4sKGjk39A1eX3slyV7nZVQD8f8waai6kJ0ySLFghSCxFx+FQKTBY44BhT4+x9X5LPGxsUE3/uuy1GLoGfJzPMFtbkRTKx1hCXg6qEBHVh7NQqPmoxuXp8PwUXKczp/p81F9MYw2cTdaIfKB7v01+h4chgnhMG9KWjhR76o=
  app: 'rightofway'
  on:
    repo: meron93/right-of-way-client
